# Generated by Django 4.1.1 on 2022-11-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoruser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='depertment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='educationlevel',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='male.png', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
