# Generated by Django 4.1.1 on 2022-11-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoruser', '0004_alter_profile_address_alter_profile_depertment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ongoingtuition',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pastex',
            field=models.TextField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
