# Generated by Django 4.1.1 on 2022-11-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoruser', '0006_rename_pastex_profile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
