# Generated by Django 4.1.1 on 2022-11-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoruser', '0007_alter_profile_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='male.png', upload_to='testimonial_profile_images')),
                ('name', models.CharField(max_length=20, null=True)),
                ('testimonial', models.CharField(max_length=400, null=True)),
                ('prof', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
