# Generated by Django 4.1.1 on 2022-11-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoruser', '0008_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='prof',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
