# Generated by Django 4.1.1 on 2022-11-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoruser', '0011_testimonial_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(null=True, upload_to='testimonial_profile_images'),
        ),
    ]
