# Generated by Django 4.1.1 on 2022-11-14 19:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('School', 'School'), ('College', 'College'), ('University', 'University')], max_length=50)),
                ('sclass', models.CharField(max_length=50)),
                ('Vtype', models.CharField(choices=[('English V', 'English V'), ('Bangla V', 'Bangla V'), ('Arabic V', 'Arabic V')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('overview', ckeditor.fields.RichTextField()),
                ('location', models.CharField(max_length=150)),
                ('section', models.CharField(choices=[('Science', 'Science'), ('Arts', 'Arts'), ('Business', 'Business'), ('Other', 'Other')], max_length=50)),
                ('uni', models.CharField(max_length=50)),
                ('teacherdpt', models.CharField(max_length=50)),
                ('teacherback', models.CharField(choices=[('English V', 'English V'), ('Bangla V', 'Bangla V'), ('Arabic V', 'Arabic V')], max_length=50)),
                ('teachergender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('salary', models.PositiveIntegerField(default=3000)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(default='Available', max_length=20)),
            ],
        ),
    ]
