# Generated by Django 4.1.1 on 2022-11-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('NotAvailable', 'NotAvailable'), ('Pending', 'Pending'), ('Other', 'Other')], default='Available', max_length=20),
        ),
    ]
