# Generated by Django 4.1.1 on 2022-11-15 07:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_job_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('cv', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('cv', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
