# Generated by Django 4.1.1 on 2022-11-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_teacher_name_alter_teacher_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
