# Generated by Django 4.1.1 on 2022-11-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_job_aplicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplications',
            name='appliedtuition',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
