# Generated by Django 4.1.1 on 2022-11-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_aplications_tuitionid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aplications',
            new_name='Aplication',
        ),
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Teacher_to_focus',
        ),
    ]
