# Generated by Django 4.1.1 on 2022-11-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rename_aplications_aplication_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher_to_focus',
            new_name='Teacher_To_Focu',
        ),
    ]
